#!/bin/bash
set -eu

cmd=${1:-}

if test ! "$cmd"; then
    echo "command required"
    echo
    echo "available commands:"
    # alphabetical order
    echo "  build.all    build project from scratch"
    echo "  build.image  build Docker image for releases"
    echo "  build        build project"
    echo "  clean        deletes all generated files"
    echo "  coverage     run tests, then show coverage report"
    echo "  fixtures     build/regenerate test fixtures"
    echo "  lint         run code linter"
    echo "  release      build project for distribution"
    echo "  test         run tests"
    echo "  update-deps  update project dependencies"
    exit 1
fi

shift
rest=$*

if test "$cmd" = ""; then
    exit 1
    
elif test "$cmd" = "build.all"; then
    # CGO_ENABLED=0 skips CGO and linking against glibc to build static binaries.
    # -a 'build all'
    # -v 'verbose'
    ./manage.sh clean
    go build \
        -C strongbox \
        -a \
        -v
    echo "wrote ./strongbox/strongbox"
    exit 0

elif test "$cmd" = "build.image"; then
    sudo systemctl start docker
    docker build -f Dockerfile . -t strongbox8-builder

    exit 0    
    
elif test "$cmd" = "build"; then
    ./manage.sh clean
    # -C Change to dir before running the command.
    # -v 'verbose'
    go build \
        -C strongbox \
        -v
    echo "wrote ./strongbox/strongbox"
    exit 0

elif test "$cmd" = "clean"; then
    if [ ! -d "atk" ]; then
        git clone https://github.com/torkus/atk
    fi

    # files
    tbd=(
        "strongbox/linux-amd64" "strongbox/linux-amd64.sha256" # generated by 'release'
        "strongbox/strongbox" "strongbox/linux-amd64.sha256" # generated by 'build'
        "bw/coverage.out" "bw/coverage.html" "strongbox/coverage.out" "strongbox/coverage.html" # generated by 'coverage'
        "coverage" "coverage.html"
    )
    for fname in "${tbd[@]}"; do
        if [ -f "$fname" ]; then
            rm -f "$fname"
            echo "deleted file '$fname'"
        fi
    done

    # dirs
    tbd=(
        "strongbox/release" "squashfs-root" "release" "AppDir" # generated by 'release'
        "unit" # generated by 'coverage'
    )
    for dirname in "${tbd[@]}"; do
        if [ -d "$dirname" ]; then
            rm -rf "$dirname"
            echo "deleted directory '$dirname'"
        fi
    done
    exit 0

elif test "$cmd" = "coverage"; then
    mkdir -p ./unit
    # -cover 'enable coverage analysis'
    # -args -test.gocoverdir= 'write binary coverage data to this dir'
    xvfb=""
    if test -z "${DISPLAY:-}"; then
        xvfb="xvfb-run -a"
    fi
    $xvfb go test -timeout=120s -cover ./strongbox/... -args -test.gocoverdir="$PWD/unit"
    $xvfb go test -timeout=30s -cover ./bw/... -args -test.gocoverdir="$PWD/unit"
    # convert coverage data in 'unit' dir to a textual format
    go tool covdata textfmt -i=unit/ -o coverage
    # generate a html report from textual coverage data
    # -html
    go tool cover -html=coverage -o coverage.html

    # Extract total coverage percentage
    total=$(go tool cover -func=coverage | grep total | awk '{print substr($3, 1, length($3)-1)}')
    threshold=79.0

    echo "---"
    echo "Total: ${total}%"
    echo "Threshold: ${threshold}%"
    echo "---"

    echo "wrote ./unit"
    echo "wrote ./coverage"
    echo "wrote ./coverage.html"

    if (( $(echo "$total < $threshold" | bc -l) )); then
        echo "---"
        echo "Coverage $total% is below threshold of $threshold%"
        exit 1
    fi

    exit 0

elif test "$cmd" = "fixtures"; then
    # generate zip files
    (
        cd strongbox/src/testdata/zipfiles
        rm -f ./*.zip
	# lol: https://stackoverflow.com/questions/3774278/extracting-a-7-zip-file-silently-command-line-option#answer-11629736
	# 'a' add files to archive
	# '-tzip' is '-t{Type}'
	# '-w' set cwd
        7z a -tzip everyaddon--1-2-3.zip -w everyaddon--1-2-3/. | grep 'ing archive'
        7z a -tzip everyaddon--1-2-4.zip -w everyaddon--1-2-4/. | grep 'ing archive'
        7z a -tzip everyaddon--7-8-9.zip -w everyaddon--7-8-9/. | grep 'ing archive'
    )
    exit 0

elif test "$cmd" = "lint"; then
    (cd bw && go fix ./... && go fmt ./... && go mod tidy)
    (cd strongbox && go fix ./... && go fmt ./... && go mod tidy)
    # go install github.com/mgechev/revive@latest
    revive --config ./revive.toml --formatter friendly ./bw/... ./strongbox/...
    exit 0

elif test "$cmd" = "release"; then
    sudo systemctl start docker
    sudo modprobe fuse
    docker run \
	   --rm \
	   --device /dev/fuse \
	   -v "$PWD":/app \
	   -w /app \
	   --privileged \
	   strongbox8-builder

    exit 0

elif test "$cmd" = "test"; then
    # GUI tests need an X display. without one, run them under a virtual display.
    # -a 'pick a free display number'
    xvfb=""
    if test -z "${DISPLAY:-}"; then
        xvfb="xvfb-run -a"
    fi
    # -race 'detect data races'. checkptr, which -race turns on, is off: the atk fork passes
    # integer handles to C as pointers and fails it before any test runs.
    race="-race -gcflags=all=-d=checkptr=0"
    # -v verbose
    # -timeout applies to each package's whole test binary, not to individual tests.
    # the 'strongbox' main package drives the GUI through whole workflows and needs longer.
    (
        cd strongbox
        $xvfb go test \
            -v \
            $race \
            -timeout=120s \
            .
        # every package except the 'strongbox' main package
        go test \
            -v \
            $race \
            -timeout=60s \
            $(go list ./... | grep -v '^strongbox$')
    )
    (
        cd bw
        $xvfb go test \
            -v \
            $race \
            -timeout=60s \
            ./...
    )
    # Run Tcl/Tk tests
    echo "Running Tcl/Tk tests..."
    tclsh bw/ui/tcl-tk/tests/run-tests.tcl
    exit 0


elif test "$cmd" = "update-deps"; then
    # -u 'update modules [...] to use newer minor or patch releases when available'
    (
        cd strongbox
        go get -u
        go mod tidy
    )
    (
        cd bw
        go get -u
        go mod tidy
    )
    ./manage.sh build
    exit 0

# ...

fi

echo "unknown command: $cmd"
exit 1
